### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by klarstil** [feross/oculus-drone#2]
Hey guys,

thank for your great work, but I've run it some problems to fully get it up and running. Is it possible to provide a small installation guide?

Best regards

**Comment by feross** [comment]
Hey there,

This project is still very much hackathon quality code, so it's a bit tricky to get it running. I'm cc'ing the other team members (@abi, @dcposch, @jhiesey) in case any of them has more time to help elaborate.

There's an Xcode project in there somewhere that you need to run first. It gathers data points from the oculus headset and sends them over a TCP socket to anyone who connects. Then you run the node server which connects to the first server and uses the data to control the drone over wifi. You need to already be connected to the drone's wifi hotspot when you run the node server. Then you visit http://localhost:3000, I believe, and you get the live video feed there. Fullscreen your web browser to fill up the Oculus's display and you're good to go.

Use up/down (or maybe W/S) keys to control elevation since the oculus only has six axes. Once you're at a good elevation, then use the oculus for all control. Tilt extra far in one direction to do a flip in that direction.

It works best in huge, wide open spaces.
